language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5"
notifications:
  email:
    - ykhalinsky@aconex.com
    - moliveira@aconex.com
