#!/usr/bin/env node

process.title = 'drakov';

var drakov = require('./lib/drakov');
var args = require('./lib/arguments');
var watcher = require('./lib/watcher');

var argv = args.getArgv();
if (argv.watch) {
    watcher.watch(argv, function(err) {
        if (err) {
            throw err;
        }
        drakov.run(argv);
    });
} else {
    drakov.run(argv);
}
