#!/usr/bin/env node

process.title = 'drakov';

var drakov = require('./build/drakov');
var watcher = require('./build/watcher');
var args = require('./build/arguments');

var argv = args.getArgv();
drakov.run(argv, function() {
    watcher(argv);
});
