# Demo Group 1

## Simple request [/demo2]

### demo schema [GET]

+ Response 200 (application/json)

    + Schema
    
        ```json
            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "required": ["question", "choices"],
              "type": "object",
              "properties": {
                "question": {
                  "type": "string"
                },
                "choices": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "minItems": 2
                }
              }
             
            }
        ```
