# Headers

## Headers request [/headers]

### Headers schema [GET]

+ Response 200 (application/json)

    + Schema
    
        ```json
            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "string"
            }
        ```
        
## Headers with types [/header-types/{test_type}]

### GET

+ Request
    + Headers
      
              stringRequired: (string)
              numberRequired: (number)
              stringOptional: (string, optional)
              value: some value
    
+ Response 200
