# Group 1

## Simple request [/demo]

### valid demo [GET]

+ Response 200 (application/json)

    + Body

        ```json
            {
                "id": "valid1"
            }
        ```

### demo [POST]
Valid request/response pair

+ Request

    + Body
   
         ```json
            {
                "requestProp": "validProp"
            }
        ```

+ Response 200 (application/json)

    + Body

        ```json
            {
                "id": "validPair"
            }
        ```

+ Request
 Good request, bad response

    + Body
   
         ```json
            {
                "requestProp": "bad prop"
            }
        ```

+ Response 200 (application/json)

    + Body

        ```json
            {
                "notId": "good request bad response"
            }
        ```

### Bad Request [PUT]
Bad request good response
+ Request

    + Body
   
         ```json
            {
                "notRequestProp": "this is wrong"
            }
        ```

+ Response 200 (application/json)

    + Body

        ```json
            {
               "id": "bad request good response"
            }
        ```

## Request with path parameter specified wrong type [/demo1/path-param]

### Get [GET] 
+ Response 200 (application/json)

    + Body

        ```json
            {
                "id": "path value wrong type"
            }
        ```

## Request with path parameter specified correct type [/demo/123]

### Get [GET] 
+ Response 200 (application/json)

    + Body

        ```json
            {
                "id": "path value valid"
            }
        ```

## Request with path parameter left as variable but not specified [/demo2/{pathparam}]

### Get  [GET] 
+ Response 200 (application/json)

    + Body

        ```json
            {
                "id": "param unspecified"
            }
        ```

## Request with path parameter left as variable specified correctly [/demo/{pathparam}]

+ Parameters
    + pathparam (number)

### Get  [GET] 
+ Response 200 (application/json)

    + Body

        ```json
            {
                "id": "number param"
            }
        ```
        
## Request path param as value [/demo/detail]

### Get [GET] 
+ Response 200 (application/json)
    + Body

        ```json
            {
                "id": "path parameter value"
            }
        ```

## Request with query parameter as variable [/demo{?query}]

### query parameters [GET]
+ Response 200 (application/json)

    + Body

        ```json
            {
                "id": "query variable"
            }
        ```
        
## Request with query parameter with defined value [/demo?query=value]

### Request with query parameters [GET]
+ Response 200 (application/json)

    + Body

        ```json
            {
                "id": "query value"
            }
        ```

# Group 2

## Request not in contract [/unknown]

### Unknown [GET]

+ Response 200 (application/json)
    + Body

        ```json
            {
                "id": "unknown"
            }
        ```
