# Headers Group 1

## Headers request [/headers]

### Headers schema [GET]

+ Response 200 (application/json)

    + Body
    
        ```json
        "No Header"
        ```

+ Request

    + Headers
    
            id: header


+ Response 200 (application/json)

    + Body
    
        ```json
        "Has Header"
        ```
