# Group 1

## Simple request [/demo2]

### valid demo [GET]

+ Response 200 (application/json)

    + Body

        ```json
            {
                "question": "Why?",
                "choices": ["Why not?", "BECAUSE!"]
            }
        ```

